#!/bin/sh

echo "Script $0 triggered ..."

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
echo "Starting ruff analysis..."

# quietly run ruff
ruff . --fix

# use return code to abort commit if necessary
if [ $? != "0" ]; then
    echo "Commit aborted. Fix linter issues found by ruff before committing."
    exit 1
fi

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
echo "Starting isort analysis using configuration from setup.cfg..."

# recursively run isort on distance_explainer/ directory, don't try to automatically fix anything
isort --recursive distance_explainer

if [ $? != "0" ]; then
    echo "Commit aborted. Fix import issues found by isort before committing"
    exit 1
fi

echo "Pre-commit checks completed successfully."
exit 0
