name: "Install test and build"
description: "Installs python, the current package and its dependencies and runs tests and builds the package."
inputs:
  python-version:
    required: false
    default: "3.11"

runs:
  using: "composite"
  steps:
    - name: Set up Python ${{ inputs.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ inputs.python-version }}
    - name: Python info
      shell: bash -e {0}
      run: |
        which python3
        python3 --version
    - name: Upgrade pip and install dependencies
      shell: bash {0}
      run: |
        python3 -m pip install --upgrade pip setuptools
        python3 -m pip install .[dev,publishing]
    - name: Run unit tests
      shell: bash {0}
      run: pytest -v
    - name: Verify that we can build the package
      shell: bash {0}
      run: python3 -m build
